version: "3.9"

services:
  backend:
    build:
      context: backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    command: sh -c "npm run start"
    environment:
      - NODE_ENV=production


